url: "http://mbmccormick.com"
name: Matt McCormick
description: "Program Manager at Microsoft and Computer Science graduate from Purdue University"
language: en-us

author: Matt McCormick
email: matt@mbmccormick.com

permalink: /:year/:month/:title/

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions

exclude:
  - CNAME
  - Gemfile
  - LICENSE.txt
  - README.md

google:
  analytics:
    profile: "UA-6872595-6"

disqus:
  shortname: mbmccormick

twitter:
  username: mbmccormick

linkedin:
  username: mbmccorm
