url: http://mbmccormick.com
title: Matt McCormick
description: I'm a Program Manager at Microsoft and a Computer Science graduate from Purdue University. I live in Seattle with my wife and our dog and I'm always hacking away on something.
language: en-us

author: Matt McCormick
email: matt@mbmccormick.com

twitter: mbmccormick
linkedin: mbmccorm

analytics:
    profile: UA-6872595-6

permalink: /:year/:month/:title

sitemap:
    include: ["/index.html"]

exclude: ["README.md"]
